// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/cjmarkham/GoBB/config"
	"github.com/cjmarkham/GoBB/src"
	"github.com/cjmarkham/GoBB/src/controller"
	forum4 "github.com/cjmarkham/GoBB/src/controller/forum"
	"github.com/cjmarkham/GoBB/src/controller/home"
	forum2 "github.com/cjmarkham/GoBB/src/domain/forum"
	"github.com/cjmarkham/GoBB/src/domain/post"
	"github.com/cjmarkham/GoBB/src/domain/topic"
	"github.com/cjmarkham/GoBB/src/domain/user"
	"github.com/cjmarkham/GoBB/src/repository"
	"github.com/cjmarkham/GoBB/src/repository/forum"
	forum3 "github.com/cjmarkham/GoBB/src/repository/topic"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	postgresqlConfig, err := config.ProvidePostgresqlConfig()
	if err != nil {
		return nil, err
	}
	db := repository.ProvideClient(postgresqlConfig)
	forumRepository := forum.ProvideRepository(postgresqlConfig, db)
	service := forum2.ProvideService(forumRepository)
	homeController, err := home.ProvideController(service)
	if err != nil {
		return nil, err
	}
	repository2 := forum3.ProvideRepository(postgresqlConfig, db)
	topicService := topic.ProvideService(repository2)
	forumController, err := forum4.ProvideController(service, topicService)
	if err != nil {
		return nil, err
	}
	loggerConfig, err := config.ProvideLoggerConfig()
	if err != nil {
		return nil, err
	}
	logger, err := src.ProvideLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	router := controller.ProvideRouter(homeController, forumController, logger)
	serverConfig, err := config.ProvideServerConfig()
	if err != nil {
		return nil, err
	}
	server := src.ProvideServer(router, serverConfig)
	app := ProvideApp(server)
	return app, nil
}

// wire.go:

var configProviders = wire.NewSet(config.ProvideServerConfig, config.ProvideLoggerConfig)

var controllerProviders = wire.NewSet(home.ProvideController, forum4.ProvideController)

var serviceProviders = wire.NewSet(forum2.ProvideService, topic.ProvideService, post.ProvideService, user.ProvideService)

var repositoryProviders = wire.NewSet(config.ProvidePostgresqlConfig, repository.ProvideClient, forum.ProvideRepository, wire.Bind(new(forum2.Repository), new(*forum.Repository)), forum3.ProvideRepository, wire.Bind(new(topic.Repository), new(*forum3.Repository)))
